name: CI

on: [ push, pull_request ]

jobs:
  build-wasm:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config:
          - container: 'emscripten/emsdk:latest'
            artifactName: 'emscripten-latest'
          - container: 'emscripten/emsdk:2.0.4'
            artifactName: 'emscripten-2.0.4'         
    container: 
      image: ${{ matrix.config.container }}

    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: aquire missing tools
        run: |
          sudo apt update -y
          sudo apt install -y autotools-dev autoconf automake libtool pkg-config

      - name: add execute permission
        run: |
          chmod +x /emsdk/emsdk_env.sh
          chmod +x emlib.sh
          chmod -R +x scripts

      - name: build webp
        run: |
          ./emlib.sh build webp || true

      - name: build turbojpeg
        run: |
          ./emlib.sh build turbojpeg || true

      - name: build giflib
        run: |
          ./emlib.sh build giflib || true

      - name: build libtiff
        run: |
          ./emlib.sh build libtiff || true

      - name: build ogg
        run: |
          ./emlib.sh build ogg || true

      - name: build opus
        run: |
          ./emlib.sh build opus || true

      - name: build flatbuffers
        run: |
          ./emlib.sh build flatbuffers || true

      - name: build libopenssl
        run: |
          ./emlib.sh build libopenssl || true

      - name: build opusfile
        run: |
          ./emlib.sh build opusfile || true

      - name: build opencv
        run: |
          ./emlib.sh build opencv || true

      - name: build ffmpeg
        run: |
          ./emlib.sh build ffmpeg || true

      - name: build libmpg123
        run: |
          ./emlib.sh build libmpg123 || true

      - name: build zlib
        run: |
          ./emlib.sh build zlib || true

      - name: build libpng
        run: |
          ./emlib.sh build libpng || true

      - name: build harfbuzz
        run: |
          ./emlib.sh build harfbuzz || true

      - name: build freetype
        run: |
          ./emlib.sh build freetype || true

      - name: build soundtouch
        run: |
          ./emlib.sh build soundtouch || true

      - name: save files
        uses: actions/upload-artifact@v2
        with:
          name: emlib-artifacts-${{ matrix.config.artifactName }}
          path: |
            include/**/*
            lib/**/*
            share/**/*
            bin/**/*
