name: CI

on: [ push, pull_request ]

jobs:
  build-wasm:
    runs-on: ubuntu-20.04
    container: 
      image: 'emscripten/emsdk:2.0.4'

    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: aquire missing tools
        run: |
          sudo apt update -y
          sudo apt install -y autotools-dev autoconf

      - name: add execute permission
        run: |
          chmod +x emlib.sh
          chmod -R +x scripts

      - name: build webp
        run: |
          ./emlib.sh build webp || true

      - name: build turbojpeg
        run: |
          ./emlib.sh build turbojpeg || true

      - name: build giflib
        run: |
          ./emlib.sh build giflib || true

      - name: build opus
        run: |
          ./emlib.sh build opus || true

      - name: build opencv
        run: |
          ./emlib.sh build opencv || true

      - name: build ffmpeg
        run: |
          ./emlib.sh build ffmpeg || true

      - name: save files
        uses: actions/upload-artifact@v2
        with:
          name: emlib-artifacts
          path: |
            include/**/*
            lib/**/*